# Generated by Django 4.0.6 on 2022-08-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'managed': True, 'ordering': ['-updated', '-created']},
        ),
    ]
