# Generated by Django 4.0.6 on 2022-08-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='nuevoUsuario',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
