# Generated by Django 4.0.6 on 2022-08-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0002_movimientos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Movimientos',
        ),
    ]
