# Generated by Django 4.0.6 on 2022-08-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_empleados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
    ]
