# Generated by Django 4.0.6 on 2022-08-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamos',
        ),
    ]
